[changelog]
body = """

## Class Widgets æ–°ç‰ˆæœ¬ï¼{% if version %}({{ version }}){%- endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits | unique(attribute="message") %}
- {% if commit.scope %}{{ commit.scope }}: {%- endif -%}{{ commit.message | upper_first }}
  {% if commit.remote.username %}by @{{ commit.remote.username }}{%- endif -%}
  {% if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}){%- endif %}
{% endfor %}
{%- endfor -%}

{%- if github -%}
{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
{% raw %}\n{% endraw -%}
## ğŸ‰ æ–°è´¡çŒ®è€…
{%- endif %}\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
* @{{ contributor.username }} {%- if contributor.pr_number %} åœ¨ [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) {%- endif %} ç¬¬ä¸€æ¬¡è´¡çŒ®
{%- endfor -%}
{%- endif -%}

{% if version %}
{% if previous.version %}
**å®Œæ•´å˜æ›´æ—¥å¿—**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
{% endif %}
{% else -%}
{% raw %}\n{% endraw %}
{% endif %}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
footer = "<!-- generated by git-cliff -->"
output = "CHANGELOG.md"
trim = true

[git]
commit_parsers = [
  {group = "âª å›æ»š", message = "^revert"},
  {group = "â™»ï¸ é‡æ„", message = "^refactor"},
  {group = "âš¡ æ€§èƒ½ä¼˜åŒ–", message = "^perf"},
  {group = "âœ¨ æ–°åŠŸèƒ½", message = "^feat"},
  {group = "ğŸ› Bug ä¿®å¤", message = "^fix"},
  {group = "ğŸ‘· CI/CD", message = "^ci"},
  {group = "ğŸ’„ æ ·å¼è°ƒæ•´", message = "^style"},
  {group = "ğŸ“š æ–‡æ¡£æ›´æ–°", message = "^docs"},
  {group = "ğŸ“¦ æ„å»º", message = "^build"},
  {group = "ğŸ”§ æ‚é¡¹", message = "^chore"}
]
conventional_commits = true
filter_commits = true
filter_unconventional = true
limit_commits = 42
link_parsers = []
protect_breaking_commits = false
sort_commits = "oldest"
split_commits = false
# tag_pattern = "v[0-9].*"
topo_order = false
