# Pre-commit-ci
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-ast
      - id: fix-byte-order-marker
      # - id: mixed-line-ending
      #   args: ["--fix=lf"]

  # - repo: https://github.com/rhysd/actionlint
  #   rev: v1.7.7
  #   hooks:
  #     - id: actionlint

  # - repo: https://github.com/crate-ci/typos
  #   rev: v1.35.5
  #   hooks:
  #     - id: typos
  #       args: ["--format", "brief"]
  #       exclude: '\.ts$'

  # - repo: https://github.com/executablebooks/mdformat
  #   rev: 0.7.22
  #   hooks:
  #     - id: mdformat

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: ["--fix", "--unsafe-fixes", "--show-fixes", "--exit-zero"]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - "-d"
          - "{extends: default, rules: {line-length: disable}}"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--write"]
        files: \.(json|md|yaml|yml)$
        additional_dependencies:
          - "prettier@3.6.2"
          - "@prettier/plugin-xml"

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.3
    hooks:
      - id: toml-sort-fix
        args: ["--all", "--in-place"]
