# Pre-commit-ci
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace # 裁剪尾随空格
      - id: end-of-file-fixer # 文件尾换行
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      # - id: check-added-large-files
      #   args: ['--maxkb=1000']
      # - id: mixed-line-ending # EOL
      #   args: ['--fix=lf']

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.12.10
  #   hooks:
  #     - id: ruff-check
  #       args: ["--fix", "--exit-non-zero-on-fix"]

  # - repo: https://github.com/rhysd/actionlint
  #   rev: v1.7.7
  #   hooks:
  #     - id: actionlint

  - repo: https://github.com/crate-ci/typos
    rev: v1.16.26
    hooks:
      - id: typos
        args: ["--format", "brief"]
        exclude: '\.ts$'

  # 格式化
  # - repo: https://github.com/executablebooks/mdformat
  #   rev: 0.7.22
  #   hooks:
  #     - id: mdformat

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - "-d"
          - "{extends: default, rules: {line-length: disable}}"

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
        args: ["--all", "--in-place"]
